@HostAddress = http://localhost:5141/
@CustomerApi = api/Customer
@PortsApi = api/Port
@VesselsApi = api/Vessels
@PortsScheduleApi = api/PortSchedule

###
GET {{HostAddress}}{{CustomerApi}}/GetCustomers
Accept: application/json

### GET BY ID
GET {{HostAddress}}{{CustomerApi}}/GetCustomerById/12
Accept: application/json

### ADD Customer
POST {{HostAddress}}{{CustomerApi}}/AddCustomer
Content-Type: application/json

{
  "name": "Liverpool",
  "address": "499 Wharf 10",
  "city": "Liverpool",
  "state": "INTL",
  "country": "UK",
  "postCode": "90028",
  "phone": "3235550456",
  "email": "harbormaster@pacificwave.net",
  "creditLimit": 1000000.00,
  "paymentTerms": "Advance",
  "createDate": "2022-07-01T00:00:00",
  "lastUpdate": "2025-03-04T00:00:00"
}

### UPDATE Customer
PUT {{HostAddress}}{{CustomerApi}}/UpdateCustomer/13
Content-Type: application/json

{
  "name": "Updated Customer III",
  "address": "499 Sunset Blvd",
  "city": "San Fransisco",
  "state": "CA",
  "country": "USA",
  "postCode": "91158",
  "phone": "3235550456",
  "email": "harbormaster@pacificwave.net",
  "creditLimit": 500000.00,
  "paymentTerms": "Net90",
  "createDate": "2022-07-01T00:00:00"
}

### DELETE Customer
DELETE {{HostAddress}}{{CustomerApi}}/DeleteCustomer/11
Content-Type: application/json

### GET ALL PORTS
GET {{HostAddress}}{{PortsApi}}/GetPorts
Accept: application/json

### Get Port By Id
GET {{HostAddress}}{{PortsApi}}/GetPortById/11
Accept: application/json

###
POST {{HostAddress}}{{PortsApi}}/AddPort
Content-Type: application/json

{
  "PortName": "Port of Test5",
  "LocationCity": "San Fransisco",
  "LocationCountry": "CN",
  "Capacity": 2000000,
  "demurrage": 575.33
}

### UPDATE PORT
PUT {{HostAddress}}{{PortsApi}}/UpdatePort/11
Content-Type: application/json

{
  "portName": "Port of Test3",
  "locationCity": "San Fransisco",
  "locationCountry": "CN",
  "capacity": 2000000,
  "demurrage": 425.00,
  "createDate": "2025-01-01T11:00:00",
  "lastUpdate": "2025-03-18T17:36:05.004582"
}

### DELETE Port
DELETE {{HostAddress}}{{PortsApi}}/DeletePort/12
Content-Type: application/json

###

GET {{HostAddress}}{{VesselsApi}}/GetVessels
Content-Type: application/json

###

